ktor:
  deployment:
    port: "${WEB_PORT:9999}"
    host: "${WEB_HOST:localhost}"
  application:
    modules:
      - com.knowledgespike.ballbyball.web.bootstrap.WebModuleKt.module

api:
  baseUrl: "${API_BASE_URL:http://localhost:8081}"