package com.knowledgespike.ballbyball.parse.database.adapter

import com.knowledgespike.ballbyball.identity.CanonicalMatchId
import com.knowledgespike.ballbyball.clishared.identity.SourceReference
import com.knowledgespike.ballbyball.types.values.PublicMatchId

import com.knowledgespike.cricketarchive.LoggerDelegate
import com.knowledgespike.ballbyball.parse.database.*
import java.io.BufferedWriter
import java.nio.file.Files
import java.nio.file.Path
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.ZoneOffset

/** Writes an executable dialect-specific SQL script with stable keys within the script. */
abstract class SqlScriptOutputAdapter(
    output: Path,
    private val dialect: SqlDialect
) : OutputAdapter {
    private val log by LoggerDelegate()
    private val writer: BufferedWriter = openWriter(output)
    private val people = mutableMapOf<String, Long>()
    private val teams = mutableMapOf<String, Team>()
    private val grounds = mutableMapOf<String, Ground>()
    private val dates = mutableMapOf<LocalDate, Int>()
    private val matches = mutableMapOf<CanonicalMatchId, Long>()
    private val matchPublicIds = mutableMapOf<CanonicalMatchId, PublicMatchId>()
    private val publicMatches = mutableMapOf<PublicMatchId, CanonicalMatchId>()
    private val sourceReferences = mutableMapOf<Long, Set<String>>()
    private val innings = mutableMapOf<Pair<Long, Int>, InningsEntity>()
    private val deliveries = mutableMapOf<Triple<Long, Long, Int>, Long>()
    private val deliveryFielders = mutableSetOf<Triple<Long, Long, Long>>()
    private var nextTeamSourceId = 1L
    private var nextGroundSourceId = 1L
    private var nextBallSourceId = 1L
    private var nextWicketSourceId = 1L
    private var nextPersonKey = 1L
    private var nextTeamKey = 1L
    private var nextGroundKey = 1L
    private var nextMatchKey = 1L
    private var nextInningsKey = 1L
    private var nextDeliveryKey = 1L
    private var nextWicketKey = 1L
    private var closed = false

    init {
        writer.appendLine("-- Generated by bbb-update-database")
        RelationalSchemaSql.writeTo(writer, dialect)
        writer.appendLine(dialect.transactionStart)
    }

    override fun findMatchKey(canonicalMatchId: CanonicalMatchId): Long? = matches[canonicalMatchId]

    override fun ensurePublicMatchId(canonicalMatchId: CanonicalMatchId, publicMatchId: PublicMatchId) {
        decideMatchWrite(canonicalMatchId, publicMatchId)
    }

    override fun sourceReferencesChanged(
        canonicalMatchId: CanonicalMatchId,
        sources: List<SourceReference>
    ): Boolean {
        val matchKey = findMatchKey(canonicalMatchId) ?: return false
        val existing = sourceReferences[matchKey] ?: return false
        return existing != sources.map { fingerprint(it) }.toSet()
    }

    override fun upsertPerson(sourceId: String, fullName: String, caId: Int): Long {
        people[sourceId]?.let { return it }
        val key = nextPersonKey++
        val (sortNamePart, otherNamePart) = getNameParts(fullName)
        write(
            RelationalWriteSupport.insertSql("people", RelationalWriteSupport.PERSON_COLUMNS),
            key,
            sourceId,
            fullName,
            sortNamePart,
            otherNamePart,
            caId
        )
        people[sourceId] = key
        return key
    }

    override fun upsertTeam(name: String): Team {
        teams[name]?.let { return it }
        val team = Team(nextTeamKey++, name)
        write(
            RelationalWriteSupport.insertSql("teams", RelationalWriteSupport.TEAM_COLUMNS),
            team.id,
            nextTeamSourceId++,
            team.name
        )
        teams[name] = team
        return team
    }

    override fun upsertGround(name: String): Ground {
        grounds[name]?.let { return it }
        val ground = Ground(nextGroundKey++, name)
        write(
            RelationalWriteSupport.insertSql("grounds", RelationalWriteSupport.GROUND_COLUMNS),
            ground.id,
            nextGroundSourceId++,
            ground.name
        )
        grounds[name] = ground
        return ground
    }

    override fun upsertDate(date: LocalDate): Int {
        dates[date]?.let { return it }
        val dimensions = RelationalWriteSupport.dateDimensions(date)
        write(
            RelationalWriteSupport.insertSql("dates", RelationalWriteSupport.DATE_COLUMNS),
            *dimensions.values().toTypedArray()
        )
        dates[date] = dimensions.dateKey
        return dimensions.dateKey
    }

    override fun insertMatch(match: MatchRecord): MatchEntity {
        val key = when (val decision = decideMatchWrite(match.canonicalMatchId, match.publicMatchId)) {
            is MatchWriteDecision.Reuse -> return MatchEntity(decision.matchKey, match.publicMatchId)
            MatchWriteDecision.Insert -> nextMatchKey++
        }
        write(
            RelationalWriteSupport.insertSql("matches", RelationalWriteSupport.MATCH_COLUMNS),
            *RelationalWriteSupport.matchValues(
                key,
                match,
                LocalDateTime.now(ZoneOffset.UTC)
            ).toTypedArray()
        )
        matches[match.canonicalMatchId] = key
        matchPublicIds[match.canonicalMatchId] = match.publicMatchId
        publicMatches[match.publicMatchId] = match.canonicalMatchId
        return MatchEntity(key, match.publicMatchId)
    }

    override fun insertSourceReferences(matchId: Long, sources: List<SourceReference>) {
        sourceReferences[matchId] = sources.map { fingerprint(it) }.toSet()
        sources.forEach { source ->
            write(
                RelationalWriteSupport.insertSql(
                    "match_source_reference",
                    RelationalWriteSupport.SOURCE_REFERENCE_COLUMNS
                ),
                *RelationalWriteSupport.sourceReferenceValues(matchId, source).toTypedArray()
            )
        }
    }


    override fun upsertInnings(
        matchId: Long,
        inningsNumber: Int,
        battingTeamId: Long,
        bowlingTeamId: Long
    ): InningsEntity {
        val lookup = matchId to inningsNumber
        innings[lookup]?.let { return it }
        val result = InningsEntity(nextInningsKey++)
        write(
            RelationalWriteSupport.insertSql("innings", RelationalWriteSupport.INNINGS_COLUMNS),
            result.id,
            matchId,
            inningsNumber,
            battingTeamId,
            bowlingTeamId
        )
        innings[lookup] = result
        return result
    }

    override fun findDeliveryKey(matchId: Long, inningsId: Long, inningsOrder: Int): Long? =
        deliveries[Triple(matchId, inningsId, inningsOrder)]

    override fun insertDelivery(delivery: DeliveryRecord): Long {
        val key = nextDeliveryKey++
        write(
            RelationalWriteSupport.insertSql("deliveries", RelationalWriteSupport.DELIVERY_COLUMNS),
            *RelationalWriteSupport.deliveryValues(key, nextBallSourceId++, delivery).toTypedArray()
        )
        deliveries[Triple(delivery.matchKey, delivery.inningsKey, delivery.inningsOrder)] = key
        return key
    }

    override fun insertWicket(kind: String): Long {
        val key = nextWicketKey++
        write(
            RelationalWriteSupport.insertSql("wickets", RelationalWriteSupport.WICKET_COLUMNS),
            key,
            nextWicketSourceId++,
            kind
        )
        return key
    }

    override fun insertDeliveryWicket(deliveryId: Long, wicketId: Long) {
        write(
            RelationalWriteSupport.insertSql("delivery_wickets", RelationalWriteSupport.DELIVERY_WICKET_COLUMNS),
            deliveryId,
            wicketId
        )
    }

    override fun insertDeliveryFielder(deliveryId: Long, wicketId: Long, personId: Long) {
        val bridgeKey = Triple(deliveryId, wicketId, personId)
        if (!deliveryFielders.add(bridgeKey)) {
            log.warn(
                "Duplicate delivery_fielder suppressed from SQL script: deliveryId={}, wicketId={}, personId={}",
                deliveryId,
                wicketId,
                personId
            )
            return
        }
        write(
            RelationalWriteSupport.insertSql(
                "delivery_fielders",
                RelationalWriteSupport.DELIVERY_FIELDER_COLUMNS
            ) + " " + dialect.duplicateDeliveryFielderClause,
            deliveryId,
            wicketId,
            personId
        )
    }

    override fun insertMatchPerson(matchId: Long, personId: Long, roleCode: String) {
        write(
            RelationalWriteSupport.insertSql(
                "match_people",
                RelationalWriteSupport.MATCH_PERSON_INSERT_COLUMNS
            ) + " " + dialect.duplicateMatchPersonClause,
            matchId,
            personId,
            roleCode
        )
    }

    override fun writeAllPeople(people: Sequence<PersonEntity>) = people.forEach { person ->
        upsertPerson(person.id, person.name, person.caId)
    }

    override fun commit() = Unit

    override fun close() {
        if (!closed) {
            writer.appendLine("COMMIT;")
            writer.close()
            closed = true
        }
    }

    private fun decideMatchWrite(canonicalMatchId: CanonicalMatchId, publicMatchId: PublicMatchId) =
        RelationalWriteSupport.matchWriteDecision(
            canonicalMatchId = canonicalMatchId,
            publicMatchId = publicMatchId,
            existingMatchKey = matches[canonicalMatchId],
            existingPublicMatchId = matchPublicIds[canonicalMatchId]?.value,
            publicIdOwnedByAnotherMatch = publicMatches[publicMatchId]?.let { it != canonicalMatchId } ?: false
        )

    private fun write(sql: String, vararg values: Any?) {
        var statement = sql
        values.forEach { value -> statement = statement.replaceFirst("?", toSqlLiteral(value)) }
        writer.appendLine("$statement;")
    }

    private fun toSqlLiteral(value: Any?): String = when (value) {
        null -> "NULL"
        is Boolean -> dialect.booleanLiteral(value)
        is Number -> value.toString()
        is LocalDate -> "'${value}'"
        is LocalDateTime -> "'${value}'"
        else -> "'${value.toString().replace("'", "''")}'"
    }

    private companion object {
        fun openWriter(output: Path): BufferedWriter {
            output.parent?.let(Files::createDirectories)
            return Files.newBufferedWriter(output)
        }
    }
}