package com.knowledgespike.ballbyball.parse.database.adapter

import com.knowledgespike.ballbyball.identity.CanonicalMatchId
import com.knowledgespike.ballbyball.clishared.identity.SourceReference
import com.knowledgespike.ballbyball.types.values.PublicMatchId

import com.knowledgespike.cricketarchive.LoggerDelegate
import com.knowledgespike.ballbyball.parse.database.*
import java.io.BufferedWriter
import java.nio.file.Files
import java.nio.file.Path
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.ZoneOffset

/** Writes an executable dialect-specific SQL script while keeping warehouse keys stable within the script. */
abstract class SqlScriptOutputAdapter(
    output: Path,
    private val dialect: SqlDialect
) : OutputAdapter {
    private val log by LoggerDelegate()
    private val writer: BufferedWriter = openWriter(output)
    private val people = mutableMapOf<String, Long>()
    private val teams = mutableMapOf<String, Team>()
    private val grounds = mutableMapOf<String, Location>()
    private val dates = mutableMapOf<LocalDate, Int>()
    private val matches = mutableMapOf<CanonicalMatchId, Long>()
    private val matchPublicIds = mutableMapOf<CanonicalMatchId, PublicMatchId>()
    private val publicMatches = mutableMapOf<PublicMatchId, CanonicalMatchId>()
    private val sourceReferences = mutableMapOf<Long, Set<String>>()
    private val innings = mutableMapOf<Pair<Long, Int>, WarehouseInnings>()
    private val deliveries = mutableMapOf<Triple<Long, Long, Int>, Long>()
    private val deliveryFielders = mutableSetOf<Triple<Long, Long, Long>>()
    private var nextTeamSourceId = 1L
    private var nextGroundSourceId = 1L
    private var nextBallSourceId = 1L
    private var nextWicketSourceId = 1L
    private var nextPersonKey = 1L
    private var nextTeamKey = 1L
    private var nextGroundKey = 1L
    private var nextMatchKey = 1L
    private var nextInningsKey = 1L
    private var nextDeliveryKey = 1L
    private var nextWicketKey = 1L
    private var closed = false

    init {
        writer.appendLine("-- Generated by bbb-update-database")
        WarehouseSchemaSql.writeTo(writer, dialect)
        writer.appendLine(dialect.transactionStart)
    }

    override fun findMatchKey(canonicalMatchId: CanonicalMatchId): Long? = matches[canonicalMatchId]

    override fun ensurePublicMatchId(canonicalMatchId: CanonicalMatchId, publicMatchId: PublicMatchId) {
        decideMatchWrite(canonicalMatchId, publicMatchId)
    }

    override fun sourceReferencesChanged(
        canonicalMatchId: CanonicalMatchId,
        sources: List<SourceReference>
    ): Boolean {
        val matchKey = findMatchKey(canonicalMatchId) ?: return false
        val existing = sourceReferences[matchKey] ?: return false
        return existing != sources.map { fingerprint(it) }.toSet()
    }

    override fun upsertPerson(sourceId: String, fullName: String, caId: Int): Long {
        people[sourceId]?.let { return it }
        val key = nextPersonKey++
        val (sortNamePart, otherNamePart) = getNameParts(fullName)
        write(
            WarehouseWriteSupport.insertSql("dim_person", WarehouseWriteSupport.PERSON_COLUMNS),
            key,
            sourceId,
            fullName,
            sortNamePart,
            otherNamePart,
            caId
        )
        people[sourceId] = key
        return key
    }

    override fun upsertTeam(name: String): Team {
        teams[name]?.let { return it }
        val team = Team(nextTeamKey++, name)
        write(
            WarehouseWriteSupport.insertSql("dim_team", WarehouseWriteSupport.TEAM_COLUMNS),
            team.id,
            nextTeamSourceId++,
            team.name
        )
        teams[name] = team
        return team
    }

    override fun upsertGround(name: String): Location {
        grounds[name]?.let { return it }
        val ground = Location(nextGroundKey++, name)
        write(
            WarehouseWriteSupport.insertSql("dim_ground", WarehouseWriteSupport.GROUND_COLUMNS),
            ground.id,
            nextGroundSourceId++,
            ground.name
        )
        grounds[name] = ground
        return ground
    }

    override fun upsertDate(date: LocalDate): Int {
        dates[date]?.let { return it }
        val dimensions = WarehouseWriteSupport.dateDimensions(date)
        write(
            WarehouseWriteSupport.insertSql("dim_date", WarehouseWriteSupport.DATE_COLUMNS),
            *dimensions.values().toTypedArray()
        )
        dates[date] = dimensions.dateKey
        return dimensions.dateKey
    }

    override fun insertMatch(match: MatchRecord): WarehouseMatch {
        val key = when (val decision = decideMatchWrite(match.canonicalMatchId, match.publicMatchId)) {
            is MatchWriteDecision.Reuse -> return WarehouseMatch(decision.matchKey, match.publicMatchId)
            MatchWriteDecision.Insert -> nextMatchKey++
        }
        write(
            WarehouseWriteSupport.insertSql("dim_match", WarehouseWriteSupport.MATCH_COLUMNS),
            *WarehouseWriteSupport.matchValues(
                key,
                match,
                LocalDateTime.now(ZoneOffset.UTC)
            ).toTypedArray()
        )
        matches[match.canonicalMatchId] = key
        matchPublicIds[match.canonicalMatchId] = match.publicMatchId
        publicMatches[match.publicMatchId] = match.canonicalMatchId
        return WarehouseMatch(key, match.publicMatchId)
    }

    override fun insertSourceReferences(matchKey: Long, sources: List<SourceReference>) {
        sourceReferences[matchKey] = sources.map { fingerprint(it) }.toSet()
        sources.forEach { source ->
            write(
                WarehouseWriteSupport.insertSql(
                    "match_source_reference",
                    WarehouseWriteSupport.SOURCE_REFERENCE_COLUMNS
                ),
                *WarehouseWriteSupport.sourceReferenceValues(matchKey, source).toTypedArray()
            )
        }
    }

    override fun insertMatchFact(
        matchKey: Long,
        matchDateKey: Int?,
        groundKey: Long,
        durationDays: Int,
        margin: Int
    ) {
        write(
            WarehouseWriteSupport.insertSql(
                "fact_match",
                WarehouseWriteSupport.MATCH_FACT_COLUMNS,
                values = listOf("?", "?", "?", "?", "?", "1")
            ),
            matchKey,
            matchDateKey,
            groundKey,
            durationDays,
            margin
        )
    }

    override fun upsertInnings(
        matchKey: Long,
        inningsNumber: Int,
        battingTeamKey: Long,
        bowlingTeamKey: Long
    ): WarehouseInnings {
        val lookup = matchKey to inningsNumber
        innings[lookup]?.let { return it }
        val result = WarehouseInnings(nextInningsKey++)
        write(
            WarehouseWriteSupport.insertSql("dim_innings", WarehouseWriteSupport.INNINGS_COLUMNS),
            result.key,
            matchKey,
            inningsNumber,
            battingTeamKey,
            bowlingTeamKey
        )
        innings[lookup] = result
        return result
    }

    override fun findDeliveryKey(matchKey: Long, inningsKey: Long, inningsOrder: Int): Long? =
        deliveries[Triple(matchKey, inningsKey, inningsOrder)]

    override fun insertDelivery(delivery: DeliveryRecord): Long {
        val key = nextDeliveryKey++
        write(
            WarehouseWriteSupport.insertSql("fact_delivery", WarehouseWriteSupport.DELIVERY_COLUMNS),
            *WarehouseWriteSupport.deliveryValues(key, nextBallSourceId++, delivery).toTypedArray()
        )
        deliveries[Triple(delivery.matchKey, delivery.inningsKey, delivery.inningsOrder)] = key
        return key
    }

    override fun insertWicket(kind: String): Long {
        val key = nextWicketKey++
        write(
            WarehouseWriteSupport.insertSql("dim_wicket", WarehouseWriteSupport.WICKET_COLUMNS),
            key,
            nextWicketSourceId++,
            kind
        )
        return key
    }

    override fun insertDeliveryWicket(deliveryKey: Long, wicketKey: Long) {
        write(
            WarehouseWriteSupport.insertSql("bridge_delivery_wicket", WarehouseWriteSupport.DELIVERY_WICKET_COLUMNS),
            deliveryKey,
            wicketKey
        )
    }

    override fun insertDeliveryFielder(deliveryKey: Long, wicketKey: Long, personKey: Long) {
        val bridgeKey = Triple(deliveryKey, wicketKey, personKey)
        if (!deliveryFielders.add(bridgeKey)) {
            log.warn(
                "Duplicate bridge_delivery_fielder suppressed from SQL script: deliveryKey={}, wicketKey={}, personKey={}",
                deliveryKey,
                wicketKey,
                personKey
            )
            return
        }
        write(
            WarehouseWriteSupport.insertSql(
                "bridge_delivery_fielder",
                WarehouseWriteSupport.DELIVERY_FIELDER_COLUMNS
            ) + " " + dialect.duplicateDeliveryFielderClause,
            deliveryKey,
            wicketKey,
            personKey
        )
    }

    override fun insertMatchPerson(matchKey: Long, personKey: Long, roleCode: String) {
        write(
            WarehouseWriteSupport.insertSql(
                "bridge_match_person",
                WarehouseWriteSupport.MATCH_PERSON_INSERT_COLUMNS
            ) + " " + dialect.duplicateMatchPersonClause,
            matchKey,
            personKey,
            roleCode
        )
    }

    override fun writeAllPeople(people: Sequence<PersonRegistryEntity>) = people.forEach { person ->
        upsertPerson(person.id, person.name, person.caId)
    }

    override fun commit() = Unit

    override fun close() {
        if (!closed) {
            writer.appendLine("COMMIT;")
            writer.close()
            closed = true
        }
    }

    private fun decideMatchWrite(canonicalMatchId: CanonicalMatchId, publicMatchId: PublicMatchId) =
        WarehouseWriteSupport.matchWriteDecision(
            canonicalMatchId = canonicalMatchId,
            publicMatchId = publicMatchId,
            existingMatchKey = matches[canonicalMatchId],
            existingPublicMatchId = matchPublicIds[canonicalMatchId]?.value,
            publicIdOwnedByAnotherMatch = publicMatches[publicMatchId]?.let { it != canonicalMatchId } ?: false
        )

    private fun write(sql: String, vararg values: Any?) {
        var statement = sql
        values.forEach { value -> statement = statement.replaceFirst("?", toSqlLiteral(value)) }
        writer.appendLine("$statement;")
    }

    private fun toSqlLiteral(value: Any?): String = when (value) {
        null -> "NULL"
        is Boolean -> dialect.booleanLiteral(value)
        is Number -> value.toString()
        is LocalDate -> "'${value}'"
        is LocalDateTime -> "'${value}'"
        else -> "'${value.toString().replace("'", "''")}'"
    }

    private companion object {
        fun openWriter(output: Path): BufferedWriter {
            output.parent?.let(Files::createDirectories)
            return Files.newBufferedWriter(output)
        }
    }
}