ktor {
    deployment {
        port = 8081
        port = ${?API_PORT}
    }
    application {
        modules = [ com.knowledgespike.ballbyball.api.ApplicationKt.module ]
    }
}

database {
    jdbcUrl = "jdbc:mariadb://localhost:3306/acs_ball_by_ball"
    jdbcUrl = ${?DB_JDBC_URL}
    user = "acs_ball_by_ball"
    user = ${?DB_USER}
    password = ""
    password = ${?DB_PASSWORD}
    maximumPoolSize = 10
    maximumPoolSize = ${?DB_MAX_POOL_SIZE}
}