CREATE SCHEMA IF NOT EXISTS cricsheet;
SET search_path TO cricsheet;

CREATE TABLE teams
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

INSERT INTO teams (name)
VALUES ('unknown');

CREATE TABLE grounds
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(500) NOT NULL
);

CREATE TABLE personregistry
(
    personid VARCHAR(10) PRIMARY KEY,
    fullname VARCHAR(200) NOT NULL,
    caid     INTEGER      NOT NULL
);

CREATE TABLE players
(
    personid      VARCHAR(10) PRIMARY KEY,
    fullname      VARCHAR(200) NOT NULL,
    sortnamepart  VARCHAR(200) NOT NULL,
    othernamepart VARCHAR(200) NOT NULL,

    FOREIGN KEY (personid) REFERENCES personregistry (personid) ON DELETE CASCADE
);

CREATE TABLE umpires
(
    personid      VARCHAR(10) PRIMARY KEY,
    fullname      VARCHAR(200) NOT NULL,
    sortnamepart  VARCHAR(200) NOT NULL,
    othernamepart VARCHAR(200) NOT NULL,

    FOREIGN KEY (personid) REFERENCES personregistry (personid) ON DELETE CASCADE
);

CREATE TABLE reserveumpires
(
    personid      VARCHAR(10) PRIMARY KEY,
    fullname      VARCHAR(200) NOT NULL,
    sortnamepart  VARCHAR(200) NOT NULL,
    othernamepart VARCHAR(200) NOT NULL,

    FOREIGN KEY (personid) REFERENCES personregistry (personid) ON DELETE CASCADE
);

CREATE TABLE tvumpires
(
    personid      VARCHAR(10) PRIMARY KEY,
    fullname      VARCHAR(200) NOT NULL,
    sortnamepart  VARCHAR(200) NOT NULL,
    othernamepart VARCHAR(200) NOT NULL,

    FOREIGN KEY (personid) REFERENCES personregistry (personid) ON DELETE CASCADE
);

CREATE TABLE matchreferees
(
    personid      VARCHAR(10) PRIMARY KEY,
    fullname      VARCHAR(200) NOT NULL,
    sortnamepart  VARCHAR(200) NOT NULL,
    othernamepart VARCHAR(200) NOT NULL,

    FOREIGN KEY (personid) REFERENCES personregistry (personid) ON DELETE CASCADE
);

CREATE TABLE matches
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caid           VARCHAR(10)  NULL,
    filename       VARCHAR(120) NOT NULL,
    matchinseries  INTEGER      NOT NULL,
    matchtype      VARCHAR(15)  NOT NULL,
    event          VARCHAR(200) NOT NULL,
    team1id        INTEGER      NOT NULL,
    team1name      VARCHAR(200) NOT NULL,
    team2id        INTEGER      NOT NULL,
    team2name      VARCHAR(200) NOT NULL,
    matchdate      VARCHAR(200) NOT NULL,
    season         VARCHAR(200) NOT NULL,
    matchstartyear VARCHAR(200) NOT NULL,
    matchstartdate DATE         NULL,
    duration       INTEGER      NOT NULL,
    ballsperover   INTEGER      NOT NULL,
    addeddate      TIMESTAMP    NOT NULL,
    location       VARCHAR(200) NOT NULL,
    locationid     INTEGER      NOT NULL,
    tossteamid     INTEGER      NOT NULL,
    tossdecision   VARCHAR(10)  NULL,
    victorytype    VARCHAR(15)  NOT NULL,
    margin         INTEGER      NOT NULL,
    whowonid       INTEGER      NULL,
    wholostid      INTEGER      NULL,

    FOREIGN KEY (team1id) REFERENCES teams (id) ON DELETE CASCADE,
    FOREIGN KEY (team2id) REFERENCES teams (id) ON DELETE CASCADE,
    FOREIGN KEY (tossteamid) REFERENCES teams (id) ON DELETE CASCADE,
    FOREIGN KEY (whowonid) REFERENCES teams (id) ON DELETE CASCADE,
    FOREIGN KEY (wholostid) REFERENCES teams (id) ON DELETE CASCADE,
    FOREIGN KEY (locationid) REFERENCES grounds (id) ON DELETE CASCADE
);

CREATE INDEX idx_matches_matchtype ON matches (matchtype);

CREATE TABLE playersmatches
(
    personid VARCHAR(10) NOT NULL,
    matchid  INTEGER     NOT NULL,

    FOREIGN KEY (personid) REFERENCES players (personid) ON DELETE CASCADE,
    FOREIGN KEY (matchid) REFERENCES matches (id) ON DELETE CASCADE
);

CREATE TABLE umpiresmatches
(
    personid VARCHAR(10) NOT NULL,
    matchid  INTEGER     NOT NULL,

    FOREIGN KEY (personid) REFERENCES umpires (personid) ON DELETE CASCADE,
    FOREIGN KEY (matchid) REFERENCES matches (id) ON DELETE CASCADE
);

CREATE TABLE tvumpiresmatches
(
    personid VARCHAR(10) NOT NULL,
    matchid  INTEGER     NOT NULL,

    FOREIGN KEY (personid) REFERENCES tvumpires (personid) ON DELETE CASCADE,
    FOREIGN KEY (matchid) REFERENCES matches (id) ON DELETE CASCADE
);

CREATE TABLE matchrefereesmatches
(
    personid VARCHAR(10) NOT NULL,
    matchid  INTEGER     NOT NULL,

    FOREIGN KEY (personid) REFERENCES matchreferees (personid) ON DELETE CASCADE,
    FOREIGN KEY (matchid) REFERENCES matches (id) ON DELETE CASCADE
);

CREATE TABLE reserveumpiresmatches
(
    personid VARCHAR(10) NOT NULL,
    matchid  INTEGER     NOT NULL,

    FOREIGN KEY (personid) REFERENCES reserveumpires (personid) ON DELETE CASCADE,
    FOREIGN KEY (matchid) REFERENCES matches (id) ON DELETE CASCADE
);

CREATE TABLE ballbyball
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teamid        INTEGER     NOT NULL,
    opponentsid   INTEGER     NOT NULL,
    matchid       INTEGER     NOT NULL,
    inningsnumber INTEGER     NOT NULL,
    inningsorder  INTEGER     NOT NULL,
    overnumber    INTEGER     NOT NULL,
    ballnumber    INTEGER     NOT NULL,
    ballinover    INTEGER     NOT NULL,
    bowlerid      VARCHAR(10) NOT NULL,
    batterid      VARCHAR(10) NOT NULL,
    nonstrikerid  VARCHAR(10) NOT NULL,
    batterruns    INTEGER     NOT NULL,
    extraruns     INTEGER     NOT NULL,
    totalruns     INTEGER     NOT NULL,
    noballs       INTEGER     NOT NULL,
    wides         INTEGER     NOT NULL,
    byes          INTEGER     NOT NULL,
    legbyes       INTEGER     NOT NULL,
    nonboundary   INTEGER     NULL,
    powerplay     INTEGER     NOT NULL,
    wicket        INTEGER     NOT NULL,

    FOREIGN KEY (matchid) REFERENCES matches (id) ON DELETE CASCADE,
    FOREIGN KEY (teamid) REFERENCES teams (id) ON DELETE CASCADE,
    FOREIGN KEY (bowlerid) REFERENCES players (personid) ON DELETE CASCADE,
    FOREIGN KEY (batterid) REFERENCES players (personid) ON DELETE CASCADE
);

CREATE INDEX idx_ballbyball_overnumber ON ballbyball (overnumber);
CREATE INDEX idx_ballbyball_ballnumber ON ballbyball (ballnumber);
CREATE INDEX idx_ballbyball_ballinover ON ballbyball (ballinover);
CREATE INDEX idx_ballbyball_batterid ON ballbyball (batterid);
CREATE INDEX idx_ballbyball_bowlerid ON ballbyball (bowlerid);
CREATE INDEX idx_ballbyball_batterruns ON ballbyball (batterruns);
CREATE INDEX idx_ballbyball_extraruns ON ballbyball (extraruns);
CREATE INDEX idx_ballbyball_powerplay ON ballbyball (powerplay);

CREATE TABLE wickets
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(30)
);

CREATE TABLE ballswickets
(
    ballid   INTEGER NOT NULL,
    wicketid INTEGER NOT NULL,

    FOREIGN KEY (ballid) REFERENCES ballbyball (id) ON DELETE CASCADE,
    FOREIGN KEY (wicketid) REFERENCES wickets (id) ON DELETE CASCADE
);