name: Set up the JDK
description: "Sets up the JDK environment for Java/Kotlin projects"

inputs:
  java-version:
    description: "The version of Java to set up"
    required: true
    default: "21"
  distribution:
    description: "The Java distribution to use"
    required: true
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
