CREATE SCHEMA IF NOT EXISTS acs_ball_by_ball;
SET search_path TO acs_ball_by_ball;

DROP TABLE IF EXISTS bridge_delivery_fielder, bridge_delivery_wicket, bridge_match_person,
    fact_delivery, fact_match, dim_wicket, dim_innings, match_source_reference,
    dim_match, dim_ground, dim_person, dim_team, dim_date,
    BallsWickets, Wickets, BallByBall, ReserveUmpiresMatches, MatchRefereesMatches,
    TvUmpiresMatches, UmpiresMatches, PlayersMatches, Matches, MatchReferees,
    TvUmpires, ReserveUmpires, Umpires, Players, PersonRegistry, Grounds, Teams
CASCADE;

CREATE TABLE dates
(
    date_id          INTEGER     NOT NULL PRIMARY KEY,
    calendar_date    DATE        NOT NULL,
    calendar_year    SMALLINT    NOT NULL,
    calendar_quarter SMALLINT    NOT NULL,
    calendar_month   SMALLINT    NOT NULL,
    month_name       VARCHAR(9)  NOT NULL,
    week_of_year     SMALLINT    NOT NULL,
    day_of_month     SMALLINT    NOT NULL,
    day_of_week      SMALLINT    NOT NULL,
    day_name         VARCHAR(9)  NOT NULL,
    is_weekend       BOOLEAN     NOT NULL,
    CONSTRAINT uq_dates_calendar_date UNIQUE (calendar_date)
);

CREATE TABLE teams
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_team_id INTEGER      NOT NULL,
    team_name      VARCHAR(100) NOT NULL,
    CONSTRAINT uq_teams_source_id UNIQUE (source_team_id)
);
CREATE INDEX idx_teams_name ON teams (team_name);

CREATE TABLE people
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_person_id VARCHAR(10)  NOT NULL,
    full_name        VARCHAR(200) NOT NULL,
    sort_name_part   VARCHAR(200) NOT NULL,
    other_name_part  VARCHAR(200) NOT NULL,
    ca_id            INTEGER      NOT NULL,
    CONSTRAINT uq_people_source_id UNIQUE (source_person_id)
);
CREATE INDEX idx_people_full_name ON people (full_name);
CREATE INDEX idx_people_sort_name ON people (sort_name_part);
CREATE INDEX idx_people_ca_id ON people (ca_id);

CREATE TABLE grounds
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ground_id INTEGER      NOT NULL,
    ground_name      VARCHAR(500) NOT NULL,
    CONSTRAINT uq_grounds_source_id UNIQUE (source_ground_id)
);
CREATE INDEX idx_grounds_name ON grounds (ground_name);

CREATE TABLE matches
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_match_id  CHAR(36)     NULL,
    public_match_id     BIGINT       NULL,
    source_ca_id        VARCHAR(10)  NULL,
    file_name           VARCHAR(120) NOT NULL,
    match_in_series     INTEGER      NOT NULL,
    match_type          VARCHAR(15)  NOT NULL,
    event_name          VARCHAR(200) NOT NULL,
    match_date_text     VARCHAR(200) NOT NULL,
    season              VARCHAR(200) NOT NULL,
    match_start_year    VARCHAR(200) NOT NULL,
    match_start_date_id INTEGER      NULL,
    balls_per_over      INTEGER      NOT NULL,
    added_timestamp     TIMESTAMP    NOT NULL,
    team1_id            BIGINT       NOT NULL,
    team2_id            BIGINT       NOT NULL,
    ground_id           BIGINT       NOT NULL,
    toss_team_id        BIGINT       NOT NULL,
    toss_decision       VARCHAR(10)  NULL,
    victory_type        VARCHAR(15)  NOT NULL,
    winner_team_id      BIGINT       NULL,
    loser_team_id       BIGINT       NULL,
    duration_days       INTEGER      NOT NULL,
    margin              INTEGER      NOT NULL,
    match_count         SMALLINT     NOT NULL DEFAULT 1,
    CONSTRAINT uq_matches_canonical_id UNIQUE (canonical_match_id),
    CONSTRAINT uq_matches_public_id UNIQUE (public_match_id),
    CONSTRAINT fk_matches_start_date FOREIGN KEY (match_start_date_id) REFERENCES dates (date_id),
    CONSTRAINT fk_matches_team1 FOREIGN KEY (team1_id) REFERENCES teams (id),
    CONSTRAINT fk_matches_team2 FOREIGN KEY (team2_id) REFERENCES teams (id),
    CONSTRAINT fk_matches_ground FOREIGN KEY (ground_id) REFERENCES grounds (id),
    CONSTRAINT fk_matches_toss_team FOREIGN KEY (toss_team_id) REFERENCES teams (id),
    CONSTRAINT fk_matches_winner_team FOREIGN KEY (winner_team_id) REFERENCES teams (id),
    CONSTRAINT fk_matches_loser_team FOREIGN KEY (loser_team_id) REFERENCES teams (id)
);
CREATE INDEX idx_matches_type ON matches (match_type);
CREATE INDEX idx_matches_file_name ON matches (file_name);
CREATE INDEX idx_matches_type_year ON matches (match_type, match_start_year);
CREATE INDEX idx_matches_teams_type ON matches (match_type, team1_id, team2_id);
CREATE INDEX idx_matches_season ON matches (season);
CREATE INDEX idx_matches_start_date ON matches (match_start_date_id);
CREATE INDEX idx_matches_team1 ON matches (team1_id);
CREATE INDEX idx_matches_team2 ON matches (team2_id);
CREATE INDEX idx_matches_ground ON matches (ground_id);

CREATE TABLE match_source_reference
(
    match_id            BIGINT       NOT NULL,
    provider            VARCHAR(100) NOT NULL,
    provider_record_key VARCHAR(255) NOT NULL,
    source_record_id    CHAR(36)     NOT NULL,
    raw_content_digest  CHAR(64)     NOT NULL,
    CONSTRAINT pk_match_source_reference PRIMARY KEY (match_id, provider, source_record_id),
    CONSTRAINT uq_match_source_provider_record UNIQUE (provider, source_record_id),
    CONSTRAINT fk_match_source_match FOREIGN KEY (match_id) REFERENCES matches (id)
);
CREATE INDEX idx_match_source_record ON match_source_reference (source_record_id);

CREATE TABLE innings
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id        BIGINT NOT NULL,
    innings_number  INTEGER NOT NULL,
    batting_team_id BIGINT NOT NULL,
    bowling_team_id BIGINT NOT NULL,
    CONSTRAINT uq_innings_match_number UNIQUE (match_id, innings_number),
    CONSTRAINT fk_innings_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_innings_batting_team FOREIGN KEY (batting_team_id) REFERENCES teams (id),
    CONSTRAINT fk_innings_bowling_team FOREIGN KEY (bowling_team_id) REFERENCES teams (id)
);
CREATE INDEX idx_innings_batting_team ON innings (batting_team_id);
CREATE INDEX idx_innings_bowling_team ON innings (bowling_team_id);

CREATE TABLE wickets
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_wicket_id INTEGER     NOT NULL,
    wicket_kind      VARCHAR(30) NULL,
    CONSTRAINT uq_wickets_source_id UNIQUE (source_wicket_id)
);
CREATE INDEX idx_wickets_kind ON wickets (wicket_kind);

CREATE TABLE deliveries
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ball_id   INTEGER NOT NULL,
    match_id         BIGINT NOT NULL,
    match_date_id    INTEGER NULL,
    innings_id       BIGINT NOT NULL,
    batting_team_id  BIGINT NOT NULL,
    bowling_team_id  BIGINT NOT NULL,
    batter_id        BIGINT NOT NULL,
    non_striker_id   BIGINT NOT NULL,
    bowler_id        BIGINT NOT NULL,
    over_number      INTEGER NOT NULL,
    ball_number      INTEGER NOT NULL,
    ball_in_over     INTEGER NOT NULL,
    innings_order    INTEGER NOT NULL,
    batter_runs      INTEGER NOT NULL,
    extra_runs       INTEGER NOT NULL,
    total_runs       INTEGER NOT NULL,
    no_balls         INTEGER NOT NULL,
    wides            INTEGER NOT NULL,
    byes             INTEGER NOT NULL,
    leg_byes         INTEGER NOT NULL,
    non_boundary     INTEGER NULL,
    powerplay        INTEGER NOT NULL,
    wicket_count     INTEGER NOT NULL,
    CONSTRAINT uq_deliveries_source_id UNIQUE (source_ball_id),
    CONSTRAINT fk_deliveries_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_deliveries_date FOREIGN KEY (match_date_id) REFERENCES dates (date_id),
    CONSTRAINT fk_deliveries_innings FOREIGN KEY (innings_id) REFERENCES innings (id),
    CONSTRAINT fk_deliveries_batting_team FOREIGN KEY (batting_team_id) REFERENCES teams (id),
    CONSTRAINT fk_deliveries_bowling_team FOREIGN KEY (bowling_team_id) REFERENCES teams (id),
    CONSTRAINT fk_deliveries_batter FOREIGN KEY (batter_id) REFERENCES people (id),
    CONSTRAINT fk_deliveries_non_striker FOREIGN KEY (non_striker_id) REFERENCES people (id),
    CONSTRAINT fk_deliveries_bowler FOREIGN KEY (bowler_id) REFERENCES people (id)
);
CREATE INDEX idx_deliveries_match_order ON deliveries (match_id, innings_order);
CREATE INDEX idx_deliveries_match_sequence ON deliveries (match_id, innings_order, over_number, ball_in_over);
CREATE INDEX idx_deliveries_date ON deliveries (match_date_id);
CREATE INDEX idx_deliveries_innings ON deliveries (innings_id);
CREATE INDEX idx_deliveries_batting_team ON deliveries (batting_team_id);
CREATE INDEX idx_deliveries_bowling_team ON deliveries (bowling_team_id);
CREATE INDEX idx_deliveries_batter ON deliveries (batter_id);
CREATE INDEX idx_deliveries_non_striker ON deliveries (non_striker_id);
CREATE INDEX idx_deliveries_bowler ON deliveries (bowler_id);
CREATE INDEX idx_deliveries_over ON deliveries (over_number);
CREATE INDEX idx_deliveries_ball_in_over ON deliveries (ball_in_over);
CREATE INDEX idx_deliveries_powerplay ON deliveries (powerplay);

CREATE TABLE match_people
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id  BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    role_code VARCHAR(32) NOT NULL,
    CONSTRAINT uq_match_people_role UNIQUE (match_id, person_id, role_code),
    CONSTRAINT fk_match_people_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_match_people_person FOREIGN KEY (person_id) REFERENCES people (id)
);
CREATE INDEX idx_match_people_person ON match_people (person_id);
CREATE INDEX idx_match_people_role ON match_people (role_code);

CREATE TABLE delivery_wickets
(
    delivery_id BIGINT NOT NULL,
    wicket_id   BIGINT NOT NULL,
    PRIMARY KEY (delivery_id, wicket_id),
    CONSTRAINT fk_delivery_wickets_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries (id),
    CONSTRAINT fk_delivery_wickets_wicket FOREIGN KEY (wicket_id) REFERENCES wickets (id)
);
CREATE INDEX idx_delivery_wickets_wicket ON delivery_wickets (wicket_id);

CREATE TABLE delivery_fielders
(
    delivery_id BIGINT NOT NULL,
    wicket_id   BIGINT NOT NULL,
    person_id   BIGINT NOT NULL,
    PRIMARY KEY (delivery_id, wicket_id, person_id),
    CONSTRAINT fk_delivery_fielders_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries (id),
    CONSTRAINT fk_delivery_fielders_wicket FOREIGN KEY (wicket_id) REFERENCES wickets (id),
    CONSTRAINT fk_delivery_fielders_person FOREIGN KEY (person_id) REFERENCES people (id)
);
CREATE INDEX idx_delivery_fielders_wicket ON delivery_fielders (wicket_id);
CREATE INDEX idx_delivery_fielders_person ON delivery_fielders (person_id);