name: Sets up Gradle and runs a specified Gradle task
description: "Sets up Gradle and runs a specified Gradle task for Java/Kotlin projects"

inputs:
  task:
    description: "The Gradle task to run"
    required: true
    default: "build"
  working-directory:
    description: "The working directory for the Gradle build"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup and Run Gradle
      uses: gradle/actions/setup-gradle@v4
    - run: ./gradlew ${{ inputs.task }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
