package com.knowledgespike.ballbyball.parse.database.adapter

import com.knowledgespike.ballbyball.parse.database.Location
import com.knowledgespike.ballbyball.parse.database.PersonRegistryEntity
import com.knowledgespike.ballbyball.parse.database.Team
import com.knowledgespike.ballbyball.parse.database.WarehouseInnings
import com.knowledgespike.ballbyball.parse.database.WarehouseMatch
import com.knowledgespike.ballbyball.parse.database.getNameParts
import com.knowledgespike.ballbyball.parse.database.adapter.DeliveryRecord
import com.knowledgespike.ballbyball.parse.database.adapter.MatchRecord

import java.io.BufferedWriter
import java.nio.file.Files
import java.nio.file.Path
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.ZoneOffset
import java.time.temporal.WeekFields
import java.util.Locale

/** Writes an executable dialect-specific SQL script while keeping warehouse keys stable within the script. */
abstract class SqlScriptOutputAdapter(
    output: Path,
    private val dialect: SqlDialect
) : OutputAdapter {
    private val writer: BufferedWriter = openWriter(output)
    private val people = mutableMapOf<String, Long>()
    private val teams = mutableMapOf<String, Team>()
    private val grounds = mutableMapOf<String, Location>()
    private val dates = mutableMapOf<LocalDate, Int>()
    private val matches = mutableMapOf<String, Long>()
    private val innings = mutableMapOf<Pair<Long, Int>, WarehouseInnings>()
    private val deliveries = mutableMapOf<Triple<Long, Long, Int>, Long>()
    private var nextTeamSourceId = 1L
    private var nextGroundSourceId = 1L
    private var nextMatchSourceId = 1L
    private var nextBallSourceId = 1L
    private var nextWicketSourceId = 1L
    private var nextPersonKey = 1L
    private var nextTeamKey = 1L
    private var nextGroundKey = 1L
    private var nextMatchKey = 1L
    private var nextInningsKey = 1L
    private var nextDeliveryKey = 1L
    private var nextWicketKey = 1L
    private var closed = false

    init {
        writer.appendLine("-- Generated by bb-update-database")
        WarehouseSchemaSql.writeTo(writer, dialect)
        writer.appendLine(dialect.transactionStart)
    }

    override fun findMatchKey(fileName: String): Long? = matches[fileName]

    override fun upsertPerson(sourceId: String, fullName: String, caId: Int): Long {
        people[sourceId]?.let { return it }
        val key = nextPersonKey++
        val (sortNamePart, otherNamePart) = getNameParts(fullName)
        write(
            "INSERT INTO dim_person (person_key, source_person_id, full_name, sort_name_part, other_name_part, ca_id) VALUES (?, ?, ?, ?, ?, ?)",
            key,
            sourceId,
            fullName,
            sortNamePart,
            otherNamePart,
            caId
        )
        people[sourceId] = key
        return key
    }

    override fun upsertTeam(name: String): Team {
        teams[name]?.let { return it }
        val team = Team(nextTeamKey++, name)
        write(
            "INSERT INTO dim_team (team_key, source_team_id, team_name) VALUES (?, ?, ?)",
            team.id,
            nextTeamSourceId++,
            team.name
        )
        teams[name] = team
        return team
    }

    override fun upsertGround(name: String): Location {
        grounds[name]?.let { return it }
        val ground = Location(nextGroundKey++, name)
        write(
            "INSERT INTO dim_ground (ground_key, source_ground_id, ground_name) VALUES (?, ?, ?)",
            ground.id,
            nextGroundSourceId++,
            ground.name
        )
        grounds[name] = ground
        return ground
    }

    override fun upsertDate(date: LocalDate): Int {
        dates[date]?.let { return it }
        val dateKey = date.year * 10000 + date.monthValue * 100 + date.dayOfMonth
        val weekFields = WeekFields.ISO
        write(
            "INSERT INTO dim_date (date_key, calendar_date, calendar_year, calendar_quarter, calendar_month, " +
                    "month_name, week_of_year, day_of_month, day_of_week, day_name, is_weekend) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            dateKey,
            date,
            date.year,
            (date.monthValue - 1) / 3 + 1,
            date.monthValue,
            date.month.getDisplayName(java.time.format.TextStyle.FULL, Locale.ENGLISH),
            date.get(weekFields.weekOfYear()),
            date.dayOfMonth,
            date.dayOfWeek.value,
            date.dayOfWeek.getDisplayName(java.time.format.TextStyle.FULL, Locale.ENGLISH),
            date.dayOfWeek.value >= 6
        )
        dates[date] = dateKey
        return dateKey
    }

    override fun insertMatch(match: MatchRecord): WarehouseMatch {
        matches[match.fileName]?.let { return WarehouseMatch(it) }
        val key = nextMatchKey++
        write(
            "INSERT INTO dim_match (match_key, source_match_id, source_ca_id, file_name, match_in_series, match_type, event_name, " +
                    "match_date_text, season, match_start_year, match_start_date_key, balls_per_over, added_timestamp, " +
                    "team1_key, team2_key, ground_key, toss_team_key, toss_decision, victory_type, winner_team_key, loser_team_key) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            key,
            nextMatchSourceId++,
            null,
            match.fileName,
            match.matchInSeries,
            match.matchType,
            match.eventName,
            match.matchDateText,
            match.season,
            match.matchStartYear,
            match.matchStartDateKey,
            match.ballsPerOver,
            LocalDateTime.now(ZoneOffset.UTC),
            match.team1Key,
            match.team2Key,
            match.groundKey,
            match.tossTeamKey,
            match.tossDecision,
            match.victoryType,
            match.winnerTeamKey,
            match.loserTeamKey
        )
        matches[match.fileName] = key
        return WarehouseMatch(key)
    }

    override fun insertMatchFact(
        matchKey: Long,
        fileName: String,
        matchDateKey: Int?,
        groundKey: Long,
        durationDays: Int,
        margin: Int
    ) {
        write(
            "INSERT INTO fact_match (match_key, file_name, match_date_key, ground_key, duration_days, margin, match_count) VALUES (?, ?, ?, ?, ?, ?, 1)",
            matchKey,
            fileName,
            matchDateKey,
            groundKey,
            durationDays,
            margin
        )
    }

    override fun upsertInnings(
        matchKey: Long,
        inningsNumber: Int,
        battingTeamKey: Long,
        bowlingTeamKey: Long
    ): WarehouseInnings {
        val lookup = matchKey to inningsNumber
        innings[lookup]?.let { return it }
        val result = WarehouseInnings(nextInningsKey++)
        write(
            "INSERT INTO dim_innings (innings_key, match_key, innings_number, batting_team_key, bowling_team_key) VALUES (?, ?, ?, ?, ?)",
            result.key,
            matchKey,
            inningsNumber,
            battingTeamKey,
            bowlingTeamKey
        )
        innings[lookup] = result
        return result
    }

    override fun findDeliveryKey(matchKey: Long, inningsKey: Long, inningsOrder: Int): Long? =
        deliveries[Triple(matchKey, inningsKey, inningsOrder)]

    override fun insertDelivery(delivery: DeliveryRecord): Long {
        val key = nextDeliveryKey++
        write(
            "INSERT INTO fact_delivery (delivery_key, source_ball_id, match_key, match_date_key, innings_key, batting_team_key, " +
                    "bowling_team_key, batter_key, non_striker_key, bowler_key, over_number, ball_number, ball_in_over, " +
                    "innings_order, batter_runs, extra_runs, total_runs, no_balls, wides, byes, leg_byes, non_boundary, " +
                    "powerplay, wicket_count) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            key,
            nextBallSourceId++,
            delivery.matchKey,
            delivery.matchDateKey,
            delivery.inningsKey,
            delivery.battingTeamKey,
            delivery.bowlingTeamKey,
            delivery.batterKey,
            delivery.nonStrikerKey,
            delivery.bowlerKey,
            delivery.overNumber,
            delivery.ballNumber,
            delivery.ballInOver,
            delivery.inningsOrder,
            delivery.delivery.runs.batter,
            delivery.delivery.runs.extras,
            delivery.delivery.runs.total,
            delivery.delivery.extras?.noballs ?: 0,
            delivery.delivery.extras?.wides ?: 0,
            delivery.delivery.extras?.byes ?: 0,
            delivery.delivery.extras?.legbyes ?: 0,
            delivery.delivery.runs.nonBoundary?.let { if (it) 1 else 0 },
            delivery.powerplay,
            delivery.delivery.wickets.orEmpty().size
        )
        deliveries[Triple(delivery.matchKey, delivery.inningsKey, delivery.inningsOrder)] = key
        return key
    }

    override fun insertWicket(kind: String): Long {
        val key = nextWicketKey++
        write(
            "INSERT INTO dim_wicket (wicket_key, source_wicket_id, wicket_kind) VALUES (?, ?, ?)",
            key,
            nextWicketSourceId++,
            kind
        )
        return key
    }

    override fun insertDeliveryWicket(deliveryKey: Long, wicketKey: Long) {
        write("INSERT INTO bridge_delivery_wicket (delivery_key, wicket_key) VALUES (?, ?)", deliveryKey, wicketKey)
    }

    override fun insertDeliveryFielder(deliveryKey: Long, wicketKey: Long, personKey: Long) {
        write(
            "INSERT INTO bridge_delivery_fielder (delivery_key, wicket_key, person_key) VALUES (?, ?, ?)",
            deliveryKey,
            wicketKey,
            personKey
        )
    }

    override fun insertMatchPerson(matchKey: Long, personKey: Long, roleCode: String) {
        write(
            "INSERT INTO bridge_match_person (match_key, person_key, role_code) VALUES (?, ?, ?) " +
                    dialect.duplicateMatchPersonClause,
            matchKey,
            personKey,
            roleCode
        )
    }

    override fun writeAllPeople(people: Sequence<PersonRegistryEntity>) = people.forEach { person ->
        upsertPerson(person.id, person.name, person.caId)
    }

    override fun commit() = Unit

    override fun close() {
        if (!closed) {
            writer.appendLine("COMMIT;")
            writer.close()
            closed = true
        }
    }

    private fun write(sql: String, vararg values: Any?) {
        var statement = sql
        values.forEach { value -> statement = statement.replaceFirst("?", toSqlLiteral(value)) }
        writer.appendLine("$statement;")
    }

    private fun toSqlLiteral(value: Any?): String = when (value) {
        null -> "NULL"
        is Boolean -> dialect.booleanLiteral(value)
        is Number -> value.toString()
        is LocalDate -> "'${value}'"
        is LocalDateTime -> "'${value}'"
        else -> "'${value.toString().replace("'", "''")}'"
    }

    private companion object {
        fun openWriter(output: Path): BufferedWriter {
            output.parent?.let(Files::createDirectories)
            return Files.newBufferedWriter(output)
        }
    }
}