name: Build BBB-Web

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'bbb-web/**'
      - 'bbb-shared/**'
      - '.github/workflows/build-bbb-web.yml'
      - '.github/workflows/reusable-gradle.yml'
      - '.github/workflows/reusable-docker.yml'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'bbb-web/**'
      - 'bbb-shared/**'
      - '.github/workflows/build-bbb-web.yml'
    branches: [ "main" ]

jobs:
  gradle:
    uses: ./.github/workflows/reusable-gradle.yml
    with:
      working-directory: '.'
      build-task: ':bbb-web:check :bbb-web:installDist'
      upload-artifact-name: 'bbb-web-dist'
      upload-artifact-path: 'bbb-web/build/install/bbb-web'
      create-release: true

  docker-publish:
    needs: gradle
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: 'bbb-web'
      image-version: ${{ github.ref_name }}
      working-directory: '.'
      dockerfile: 'bbb-web/Dockerfile.ci'
      docker-username: ${{ vars.DOCKER_USERNAME }}
      artifact-name: 'bbb-web-dist'
      artifact-path: 'bbb-web/build/install/bbb-web'
    secrets:
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
