name: Build BBB-Update-Database

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'bbb-update-database/**'
      - 'bbb-shared/**'
      - '.github/workflows/build-bbb-update-database.yml'
      - '.github/workflows/reusable-gradle.yml'
      - '.github/workflows/reusable-docker.yml'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'bbb-update-database/**'
      - 'bbb-shared/**'
      - '.github/workflows/build-bbb-update-database.yml'
    branches: [ "main" ]

jobs:
  gradle:
    uses: ./.github/workflows/reusable-gradle.yml
    with:
      working-directory: '.'
      build-task: ':bbb-update-database:check :bbb-update-database:installDist'
      upload-artifact-name: 'bbb-update-database-dist'
      upload-artifact-path: 'bbb-update-database/build/install/bbb-update-database'

  docker-publish:
    needs: gradle
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: 'bbb-update-database'
      image-version: ${{ github.ref_name }}
      working-directory: '.'
      dockerfile: 'bbb-update-database/Dockerfile.ci'
      docker-username: ${{ vars.DOCKER_USERNAME }}
      artifact-name: 'bbb-update-database-dist'
      artifact-path: 'bbb-update-database/build/install/bbb-update-database'
    secrets:
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
