name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: Check and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: ./.github/workflows/actions/setup-jdk
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Gradle check
        uses: ./.github/workflows/actions/use-gradle
        with:
          task: 'clean check --no-daemon'
          working-directory: '.'
